//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RobEnvMK.Properties {
	using System;
	
	
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class Resources {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Resources() {
		}
		
		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RobEnvMK.Properties.Resources", typeof(Resources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Angle: .
		/// </summary>
		internal static string Angle {
			get {
				return ResourceManager.GetString("Angle", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Cmd: .
		/// </summary>
		internal static string Cmd {
			get {
				return ResourceManager.GetString("Cmd", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to ERROR: Configuration file not found..
		/// </summary>
		internal static string ErrConfigFileNotExist {
			get {
				return ResourceManager.GetString("ErrConfigFileNotExist", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Error while initializing Direct3D..
		/// </summary>
		internal static string ErrInitDirect3d {
			get {
				return ResourceManager.GetString("ErrInitDirect3d", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to ERROR: Map image does not exist..
		/// </summary>
		internal static string ErrMapImageNotExist {
			get {
				return ResourceManager.GetString("ErrMapImageNotExist", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to There is no responding robot process present, environment will be terminated..
		/// </summary>
		internal static string ErrNoRespondingProcess {
			get {
				return ResourceManager.GetString("ErrNoRespondingProcess", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to ERROR: Unable to save file..
		/// </summary>
		internal static string ErrUnableToSaveFile {
			get {
				return ResourceManager.GetString("ErrUnableToSaveFile", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to System.ApplicationException caught: .
		/// </summary>
		internal static string ExcApplication {
			get {
				return ResourceManager.GetString("ExcApplication", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Exception caught: .
		/// </summary>
		internal static string ExcCaught {
			get {
				return ResourceManager.GetString("ExcCaught", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to System.IO.FileNotFoundException caught: .
		/// </summary>
		internal static string ExcFileNotFound {
			get {
				return ResourceManager.GetString("ExcFileNotFound", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to IOException caught: .
		/// </summary>
		internal static string ExcIO {
			get {
				return ResourceManager.GetString("ExcIO", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to MKHBC Robot Maze Race v5.7.
		/// </summary>
		internal static string MyAppName {
			get {
				return ResourceManager.GetString("MyAppName", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
		/// </summary>
		internal static System.Drawing.Icon rbo_bgn {
			get {
				object obj = ResourceManager.GetObject("rbo_bgn", resourceCulture);
				return ((System.Drawing.Icon)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Robot #.
		/// </summary>
		internal static string RobotNumber {
			get {
				return ResourceManager.GetString("RobotNumber", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Browse....
		/// </summary>
		internal static string SetupBtnTxt_MapImageBrowse {
			get {
				return ResourceManager.GetString("SetupBtnTxt_MapImageBrowse", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to OK.
		/// </summary>
		internal static string SetupBtnTxt_OK {
			get {
				return ResourceManager.GetString("SetupBtnTxt_OK", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Cancel.
		/// </summary>
		internal static string SetupButtonText_Cancel {
			get {
				return ResourceManager.GetString("SetupButtonText_Cancel", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Browse....
		/// </summary>
		internal static string SetupButtonTxt_Browse {
			get {
				return ResourceManager.GetString("SetupButtonTxt_Browse", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Random.
		/// </summary>
		internal static string SetupChkBoxTextRandom {
			get {
				return ResourceManager.GetString("SetupChkBoxTextRandom", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Show on-screen info..
		/// </summary>
		internal static string SetupChkBoxTextShowOnScreenInfo {
			get {
				return ResourceManager.GetString("SetupChkBoxTextShowOnScreenInfo", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Close when all bots quit.
		/// </summary>
		internal static string SetupChkBoxTxt_CloseWhenAllBotsQuit {
			get {
				return ResourceManager.GetString("SetupChkBoxTxt_CloseWhenAllBotsQuit", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Enable HW Vertex Processing.
		/// </summary>
		internal static string SetupChkBoxTxt_EnableHWVertexProc {
			get {
				return ResourceManager.GetString("SetupChkBoxTxt_EnableHWVertexProc", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Show status window.
		/// </summary>
		internal static string SetupChkBoxTxt_ShowStatusWindow {
			get {
				return ResourceManager.GetString("SetupChkBoxTxt_ShowStatusWindow", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Visualize world.
		/// </summary>
		internal static string SetupChkBoxTxt_VisualiseWorld {
			get {
				return ResourceManager.GetString("SetupChkBoxTxt_VisualiseWorld", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Configuration Setup.
		/// </summary>
		internal static string SetupFrm_Title {
			get {
				return ResourceManager.GetString("SetupFrm_Title", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Robot start position.
		/// </summary>
		internal static string SetupGrpBoxTextRobotStartPosition {
			get {
				return ResourceManager.GetString("SetupGrpBoxTextRobotStartPosition", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Camera X:.
		/// </summary>
		internal static string SetupLbl_CameraX {
			get {
				return ResourceManager.GetString("SetupLbl_CameraX", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Camera Y:.
		/// </summary>
		internal static string SetupLbl_CameraY {
			get {
				return ResourceManager.GetString("SetupLbl_CameraY", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Camera Z:.
		/// </summary>
		internal static string SetupLbl_CameraZ {
			get {
				return ResourceManager.GetString("SetupLbl_CameraZ", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Light X:.
		/// </summary>
		internal static string SetupLbl_LightX {
			get {
				return ResourceManager.GetString("SetupLbl_LightX", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Light Y:.
		/// </summary>
		internal static string SetupLbl_LightY {
			get {
				return ResourceManager.GetString("SetupLbl_LightY", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Light Z:.
		/// </summary>
		internal static string SetupLbl_LightZ {
			get {
				return ResourceManager.GetString("SetupLbl_LightZ", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Max. idle steps:.
		/// </summary>
		internal static string SetupLbl_MaxIdleSteps {
			get {
				return ResourceManager.GetString("SetupLbl_MaxIdleSteps", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Max. stuck steps:.
		/// </summary>
		internal static string SetupLbl_MaxStuckSteps {
			get {
				return ResourceManager.GetString("SetupLbl_MaxStuckSteps", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Rotation X:.
		/// </summary>
		internal static string SetupLbl_RotationX {
			get {
				return ResourceManager.GetString("SetupLbl_RotationX", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Rotation Y:.
		/// </summary>
		internal static string SetupLbl_RotationY {
			get {
				return ResourceManager.GetString("SetupLbl_RotationY", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Rotation Z:.
		/// </summary>
		internal static string SetupLbl_RotationZ {
			get {
				return ResourceManager.GetString("SetupLbl_RotationZ", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Stuck radius:.
		/// </summary>
		internal static string SetupLbl_StuckRadius {
			get {
				return ResourceManager.GetString("SetupLbl_StuckRadius", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Look at X:.
		/// </summary>
		internal static string SetupLblLookAtX {
			get {
				return ResourceManager.GetString("SetupLblLookAtX", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Look at Y:.
		/// </summary>
		internal static string SetupLblLookAtY {
			get {
				return ResourceManager.GetString("SetupLblLookAtY", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Look at Z:.
		/// </summary>
		internal static string SetupLblLookAtZ {
			get {
				return ResourceManager.GetString("SetupLblLookAtZ", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to [ms].
		/// </summary>
		internal static string SetupLblMiliseconds {
			get {
				return ResourceManager.GetString("SetupLblMiliseconds", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Path to map image:.
		/// </summary>
		internal static string SetupLblPathToMapImg {
			get {
				return ResourceManager.GetString("SetupLblPathToMapImg", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Path to plug-in robots config:.
		/// </summary>
		internal static string SetupLblPathToPlugInCfg {
			get {
				return ResourceManager.GetString("SetupLblPathToPlugInCfg", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Size:.
		/// </summary>
		internal static string SetupLblRobotSize {
			get {
				return ResourceManager.GetString("SetupLblRobotSize", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Sight distance:.
		/// </summary>
		internal static string SetupLblSightDistance {
			get {
				return ResourceManager.GetString("SetupLblSightDistance", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Step:.
		/// </summary>
		internal static string SetupLblStep {
			get {
				return ResourceManager.GetString("SetupLblStep", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Bitmap files (*.bmp)|*.bmp|All files (*.*)|*.*.
		/// </summary>
		internal static string SetupOpenBmpDlg_Filter {
			get {
				return ResourceManager.GetString("SetupOpenBmpDlg_Filter", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Choose map.
		/// </summary>
		internal static string SetupOpenBmpDlg_Title {
			get {
				return ResourceManager.GetString("SetupOpenBmpDlg_Title", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to CFG files (*.cfg)|*.cfg|All files (*.*)|*.*.
		/// </summary>
		internal static string SetupOpenCfgDlg_Filter {
			get {
				return ResourceManager.GetString("SetupOpenCfgDlg_Filter", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Choose robots configuration file.
		/// </summary>
		internal static string SetupOpenCfgDlg_Title {
			get {
				return ResourceManager.GetString("SetupOpenCfgDlg_Title", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Stack: .
		/// </summary>
		internal static string Stack {
			get {
				return ResourceManager.GetString("Stack", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to angle:.
		/// </summary>
		internal static string Text_Angle01 {
			get {
				return ResourceManager.GetString("Text_Angle01", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to COLLISION DUMP:.
		/// </summary>
		internal static string Text_CollisionDump {
			get {
				return ResourceManager.GetString("Text_CollisionDump", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Date:.
		/// </summary>
		internal static string Text_Date01 {
			get {
				return ResourceManager.GetString("Text_Date01", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to decided to quit..
		/// </summary>
		internal static string Text_DecidedToQuit01 {
			get {
				return ResourceManager.GetString("Text_DecidedToQuit01", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to DONE..
		/// </summary>
		internal static string Text_Done01 {
			get {
				return ResourceManager.GetString("Text_Done01", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to *  Edge collided with wall at step:.
		/// </summary>
		internal static string Text_EdgeCollidedWithWallAtStep {
			get {
				return ResourceManager.GetString("Text_EdgeCollidedWithWallAtStep", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to EMPTY output queue..
		/// </summary>
		internal static string Text_EmptyOutputQueue01 {
			get {
				return ResourceManager.GetString("Text_EmptyOutputQueue01", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Exiting.
		/// </summary>
		internal static string Text_Exiting01 {
			get {
				return ResourceManager.GetString("Text_Exiting01", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to FAILED..
		/// </summary>
		internal static string Text_Failed01 {
			get {
				return ResourceManager.GetString("Text_Failed01", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to File does not exist.
		/// </summary>
		internal static string Text_FileDoesNotExist {
			get {
				return ResourceManager.GetString("Text_FileDoesNotExist", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to finished the race at position.
		/// </summary>
		internal static string Text_FinishedRaceAtPos {
			get {
				return ResourceManager.GetString("Text_FinishedRaceAtPos", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to has been killed.
		/// </summary>
		internal static string Text_HasBeenKilled01 {
			get {
				return ResourceManager.GetString("Text_HasBeenKilled01", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Hit the wall once and die..
		/// </summary>
		internal static string Text_HitTheWallOnceAndDie {
			get {
				return ResourceManager.GetString("Text_HitTheWallOnceAndDie", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to id.
		/// </summary>
		internal static string Text_Id01 {
			get {
				return ResourceManager.GetString("Text_Id01", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to is not responding or has exited..
		/// </summary>
		internal static string Text_IsNotResponding01 {
			get {
				return ResourceManager.GetString("Text_IsNotResponding01", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to killed at.
		/// </summary>
		internal static string Text_KilledAt01 {
			get {
				return ResourceManager.GetString("Text_KilledAt01", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Killing all robots....
		/// </summary>
		internal static string Text_KillingAllRobots {
			get {
				return ResourceManager.GetString("Text_KillingAllRobots", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Kill request confirmed for robot#.
		/// </summary>
		internal static string Text_KillReqConf01 {
			get {
				return ResourceManager.GetString("Text_KillReqConf01", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to name:.
		/// </summary>
		internal static string Text_Name01 {
			get {
				return ResourceManager.GetString("Text_Name01", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to There are no robots....
		/// </summary>
		internal static string Text_NoBots01 {
			get {
				return ResourceManager.GetString("Text_NoBots01", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to There is no responding robot process present..
		/// </summary>
		internal static string Text_NoRespondingBot01 {
			get {
				return ResourceManager.GetString("Text_NoRespondingBot01", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to process.
		/// </summary>
		internal static string Text_Process01 {
			get {
				return ResourceManager.GetString("Text_Process01", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to program:.
		/// </summary>
		internal static string Text_Program01 {
			get {
				return ResourceManager.GetString("Text_Program01", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Race failed. All robots died before reaching finish line..
		/// </summary>
		internal static string Text_RaceFailed {
			get {
				return ResourceManager.GetString("Text_RaceFailed", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Race failed. All robots were killed..
		/// </summary>
		internal static string Text_RaceFailed01 {
			get {
				return ResourceManager.GetString("Text_RaceFailed01", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Race participants:.
		/// </summary>
		internal static string Text_RaceParticipants {
			get {
				return ResourceManager.GetString("Text_RaceParticipants", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to                R A C E   R E S U L T S   R E P O R T.
		/// </summary>
		internal static string Text_RaceResultsReport {
			get {
				return ResourceManager.GetString("Text_RaceResultsReport", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to ------------------------------------------------------------------------------------------.
		/// </summary>
		internal static string Text_ReportDivider {
			get {
				return ResourceManager.GetString("Text_ReportDivider", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to RESET..
		/// </summary>
		internal static string Text_Reset01 {
			get {
				return ResourceManager.GetString("Text_Reset01", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Reset.
		/// </summary>
		internal static string Text_Reset02 {
			get {
				return ResourceManager.GetString("Text_Reset02", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Results:.
		/// </summary>
		internal static string Text_Results01 {
			get {
				return ResourceManager.GetString("Text_Results01", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to ROBOT BODY IN COLLISION, DUMP:.
		/// </summary>
		internal static string Text_RobotBodyInCollisionDump {
			get {
				return ResourceManager.GetString("Text_RobotBodyInCollisionDump", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Robot process.
		/// </summary>
		internal static string Text_RobotProcess01 {
			get {
				return ResourceManager.GetString("Text_RobotProcess01", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Robots config saved. Refresh/reload by pressing SHIFT+S in the main window..
		/// </summary>
		internal static string Text_RobotsConfigSaved {
			get {
				return ResourceManager.GetString("Text_RobotsConfigSaved", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Robot stuck in one position for too long will be killed..
		/// </summary>
		internal static string Text_RobotStuck01 {
			get {
				return ResourceManager.GetString("Text_RobotStuck01", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Robot will be killed..
		/// </summary>
		internal static string Text_RobotWillBeKilled01 {
			get {
				return ResourceManager.GetString("Text_RobotWillBeKilled01", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Rules:.
		/// </summary>
		internal static string Text_Rules01 {
			get {
				return ResourceManager.GetString("Text_Rules01", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to start:.
		/// </summary>
		internal static string Text_Start01 {
			get {
				return ResourceManager.GetString("Text_Start01", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to step.
		/// </summary>
		internal static string Text_Step01 {
			get {
				return ResourceManager.GetString("Text_Step01", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Stopping process.
		/// </summary>
		internal static string Text_StoppingProcess {
			get {
				return ResourceManager.GetString("Text_StoppingProcess", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to STUCK..
		/// </summary>
		internal static string Text_Stuck01 {
			get {
				return ResourceManager.GetString("Text_Stuck01", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Stuck bot radius:.
		/// </summary>
		internal static string Text_StuckBotRadius {
			get {
				return ResourceManager.GetString("Text_StuckBotRadius", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Stuck counter.
		/// </summary>
		internal static string Text_StuckCounter01 {
			get {
				return ResourceManager.GetString("Text_StuckCounter01", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to SUCCESS! The GOAL point has been reached..
		/// </summary>
		internal static string Text_SuccessGoalReached {
			get {
				return ResourceManager.GetString("Text_SuccessGoalReached", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to TIMEOUT..
		/// </summary>
		internal static string Text_Timeout01 {
			get {
				return ResourceManager.GetString("Text_Timeout01", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Too many idle steps..
		/// </summary>
		internal static string Text_TooManyIdleSteps01 {
			get {
				return ResourceManager.GetString("Text_TooManyIdleSteps01", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to will be terminated..
		/// </summary>
		internal static string Text_WillBeTerminated01 {
			get {
				return ResourceManager.GetString("Text_WillBeTerminated01", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to WARNING: Robot exec. image not found..
		/// </summary>
		internal static string WarnRobotImageNotExist {
			get {
				return ResourceManager.GetString("WarnRobotImageNotExist", resourceCulture);
			}
		}
	}
}
